// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jildokgjrgrzfgucqran.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppbGRva2dqcmdyemZndWNxcmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTI1ODksImV4cCI6MjA3MzM4ODU4OX0.88LXdz4qfC9EiTaU7eMdmiw-5o9EFFp6pX76uLqGsC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});